CREATE TABLE IF NOT EXISTS raw_flights_msp_2024 (
    year INT,
    quarter INT,
    month INT,
    dayof_month INT,
    day_of_week INT,
    flight_date DATE,
    reporting_airline VARCHAR(10),
    tail_number VARCHAR(20),
    flight_number_reporting_airline VARCHAR(20),
    origin VARCHAR(10),
    origin_city_name VARCHAR(100),
    dest VARCHAR(10),
    dest_city_name VARCHAR(100),
    crs_dep_time INT,
    dep_time INT,
    dep_delay DECIMAL(10,2),
    dep_delay_minutes DECIMAL(10,2),
    dep_del15 DECIMAL(10,2),
    taxi_out DECIMAL(10,2),
    crs_arr_time INT,
    arr_time INT,
    arr_delay DECIMAL(10,2),
    arr_delay_minutes DECIMAL(10,2),
    arr_del15 DECIMAL(10,2),
    cancelled DECIMAL(10,2),
    cancellation_code VARCHAR(5),
    diverted DECIMAL(10,2),
    crs_elapsed_time DECIMAL(10,2),
    actual_elapsed_time DECIMAL(10,2),
    air_time DECIMAL(10,2),
    flights DECIMAL(10,2),
    distance DECIMAL(10,2),
    carrier_delay DECIMAL(10,2),
    weather_delay DECIMAL(10,2),
    nas_delay DECIMAL(10,2),
    security_delay DECIMAL(10,2),
    late_aircraft_delay DECIMAL(10,2),
    source_file VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS raw_weather_kmsp_2024 (
    station VARCHAR(30),
    date DATETIME,
    name VARCHAR(255),
    report_type VARCHAR(20),
    source VARCHAR(20),
    hourly_dry_bulb_temperature VARCHAR(30),
    hourly_dew_point_temperature VARCHAR(30),
    hourly_relative_humidity VARCHAR(30),
    hourly_precipitation VARCHAR(30),
    hourly_present_weather_type TEXT,
    hourly_sky_conditions TEXT,
    hourly_visibility VARCHAR(30),
    hourly_wind_speed VARCHAR(30),
    hourly_wind_gust_speed VARCHAR(30),
    daily_average_dry_bulb_temperature VARCHAR(30),
    daily_maximum_dry_bulb_temperature VARCHAR(30),
    daily_minimum_dry_bulb_temperature VARCHAR(30),
    daily_average_wind_speed VARCHAR(30),
    daily_peak_wind_speed VARCHAR(30),
    daily_precipitation VARCHAR(30),
    daily_snowfall VARCHAR(30),
    daily_snow_depth VARCHAR(30),
    daily_weather TEXT,
    source_file VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS stg_flights_msp_daily (
    date DATE PRIMARY KEY,
    scheduled_departures INT,
    completed_departures INT,
    cancelled_departures INT,
    cancellation_rate DECIMAL(10,4),
    diverted_departures INT,
    avg_dep_delay_minutes DECIMAL(10,2),
    avg_arr_delay_minutes DECIMAL(10,2),
    delayed_15_count INT,
    delayed_15_rate DECIMAL(10,4),
    total_carrier_delay_minutes DECIMAL(12,2),
    total_weather_delay_minutes DECIMAL(12,2),
    total_nas_delay_minutes DECIMAL(12,2),
    total_security_delay_minutes DECIMAL(12,2),
    total_late_aircraft_delay_minutes DECIMAL(12,2),
    avg_taxi_out_minutes DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS stg_weather_kmsp_daily (
    date DATE PRIMARY KEY,
    weather_obs_count INT,
    avg_temp_f DECIMAL(10,2),
    min_temp_f DECIMAL(10,2),
    max_temp_f DECIMAL(10,2),
    precip_total_inches DECIMAL(10,3),
    avg_wind_speed_mph DECIMAL(10,2),
    max_wind_gust_mph DECIMAL(10,2),
    min_visibility_miles DECIMAL(10,2),
    hours_with_precip INT,
    hours_with_snow INT,
    hours_with_fog INT,
    hours_with_thunder INT,
    snow_day_flag TINYINT,
    fog_day_flag TINYINT,
    thunder_day_flag TINYINT,
    low_visibility_day_flag TINYINT,
    high_wind_day_flag TINYINT,
    precip_day_flag TINYINT,
    severe_weather_day TINYINT,
    weather_category VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS mart_msp_daily_weather_flights (
    date DATE PRIMARY KEY,
    month INT,
    month_name VARCHAR(20),
    season VARCHAR(20),
    temp_bucket VARCHAR(20),
    delay_bucket VARCHAR(20),
    scheduled_departures INT,
    completed_departures INT,
    cancelled_departures INT,
    cancellation_rate DECIMAL(10,4),
    cancellation_rate_pct DECIMAL(10,2),
    diverted_departures INT,
    avg_dep_delay_minutes DECIMAL(10,2),
    avg_arr_delay_minutes DECIMAL(10,2),
    delayed_15_count INT,
    delayed_15_rate DECIMAL(10,4),
    delayed_15_rate_pct DECIMAL(10,2),
    total_carrier_delay_minutes DECIMAL(12,2),
    total_weather_delay_minutes DECIMAL(12,2),
    total_nas_delay_minutes DECIMAL(12,2),
    total_security_delay_minutes DECIMAL(12,2),
    total_late_aircraft_delay_minutes DECIMAL(12,2),
    avg_taxi_out_minutes DECIMAL(10,2),
    weather_obs_count INT,
    avg_temp_f DECIMAL(10,2),
    min_temp_f DECIMAL(10,2),
    max_temp_f DECIMAL(10,2),
    precip_total_inches DECIMAL(10,3),
    avg_wind_speed_mph DECIMAL(10,2),
    max_wind_gust_mph DECIMAL(10,2),
    min_visibility_miles DECIMAL(10,2),
    hours_with_precip INT,
    hours_with_snow INT,
    hours_with_fog INT,
    hours_with_thunder INT,
    snow_day_flag TINYINT,
    fog_day_flag TINYINT,
    thunder_day_flag TINYINT,
    low_visibility_day_flag TINYINT,
    high_wind_day_flag TINYINT,
    precip_day_flag TINYINT,
    severe_weather_day TINYINT,
    weather_category VARCHAR(50)
);
